title: Coding for Smarties
description: Coding musings for the seasoned developer, amongst other things
show_downloads: false

baseurl: "/coding-for-smarties" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://gregsdennis.github.io" # change this to the base hostname & protocol for your site

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%-d %b, %Y"

theme: # leave it empty

# social
author: Greg Dennis
image: /thumbnail-jumbo.png
twitter:
  username: gregsdennis
slack:
  name: Manatee Open Source on Slack
  join_link: https://join.slack.com/t/manateeopensource/shared_invite/enQtMzU4MjgzMjgyNzU3LWZjYzAzYzY3NjY1MjY3ODI0ZGJiZjc3Nzk1MDM5NTNlMjMyOTE0MzMxYWVjMjdiOGU1NDY5OGVhMGQ5YzY4Zjg
github:
  username: gregsdennis

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'contact']

exclude:
  - README.md
  - _content/
  - run.bat
  - draft/
